- name: Warrior
  filepath: walk.png
  size: 48
  type: walk
  framecount: 6
- name: Warrior
  filepath: attack.png
  size: 48
  type: attack
  framecount: 4
- name: Warrior
  filepath: death.png
  size: 48
  type: death
  framecount: 4
- name: Woodcutter
  filepath: walk.png
  size: 48
  type: walk
  framecount: 6
- name: Woodcutter
  filepath: attack.png
  size: 48
  type: attack
  framecount: 6
- name: Woodcutter
  filepath: death.png
  size: 48
  type: death
  framecount: 6
- name: SteamMan
  filepath: walk.png
  size: 48
  type: walk
  framecount: 6
- name: SteamMan
  filepath: attack.png
  size: 48
  type: attack
  framecount: 6
- name: SteamMan
  filepath: death.png
  size: 48
  type: death
  framecount: 6
- name: GraveRobber
  filepath: walk.png
  size: 48
  type: walk
  framecount: 6
- name: GraveRobber
  filepath: attack.png
  size: 48
  type: attack
  framecount: 6
- name: GraveRobber
  filepath: death.png
  size: 48
  type: death
  framecount: 6
- name: Treasure
  filepath: chest.png
  size: 48
  type: item
  framecount: 1
- name: HealthPack
  filepath: heart.png
  size: 48
  type: item
  framecount: 1
- name: Swamp
  filepath: Swamp.png
  size: 32
  type: tile
  framecount: 1
- name: StoneField
  filepath: StoneField.png
  size: 32
  type: tile
  framecount: 1
