- item:
    object:
      gridx: 6
      gridy: 3
      size: 1
    value: 50
    used: false
- item:
    object:
      gridx: 16
      gridy: 2
      size: 1
    value: 50
    used: false
- item:
    object:
      gridx: 31
      gridy: 22
      size: 1
    value: 75
    used: false
- item:
    object:
      gridx: 15
      gridy: 16
      size: 1
    value: 60
    used: false
