- entity:
    object:
      gridx: 6
      gridy: 4
      size: 2
    name: Gorgon
    defense: 2
    maxhealth: 75
    currenthealth: 75
    gold: 32
    experiencevalue: 32
  attacker:
    attackpower: 4
- entity:
    object:
      gridx: 30
      gridy: 25
      size: 2
    name: Gorgon Lord
    defense: 3
    maxhealth: 100
    currenthealth: 100
    gold: 32
    experiencevalue: 32
  attacker:
    attackpower: 5
- entity:
    object:
      gridx: 22
      gridy: 13
      size: 1
    name: Barbol
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
- entity:
    object:
      gridx: 10
      gridy: 10
      size: 1
    name: Barbol Prime
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
- entity:
    object:
      gridx: 7
      gridy: 10
      size: 1
    name: Barbol Ardent
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
- entity:
    object:
      gridx: 10
      gridy: 25
      size: 2
    name: Barbol Matriarch
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
