- entity:
    object:
      xpos: 120
      ypos: 90
      size: 32
    name: Gorgon
    defense: 2
    maxhealth: 75
    currenthealth: 75
    gold: 32
    experiencevalue: 32
  attacker:
    attackpower: 4
- entity:
    object:
      xpos: 600
      ypos: 500
      size: 32
    name: Gorgon Lord
    defense: 3
    maxhealth: 100
    currenthealth: 100
    gold: 32
    experiencevalue: 32
  attacker:
    attackpower: 5
- entity:
    object:
      xpos: 450
      ypos: 150
      size: 16
    name: Barbol
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
- entity:
    object:
      xpos: 200
      ypos: 200
      size: 16
    name: Barbol Prime
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
- entity:
    object:
      xpos: 150
      ypos: 209
      size: 16
    name: Barbol Ardent
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
- entity:
    object:
      xpos: 200
      ypos: 500
      size: 16
    name: Barbol Matriarch
    defense: 3
    maxhealth: 40
    currenthealth: 40
    gold: 16
    experiencevalue: 16
  attacker:
    attackpower: 2
