- iteminfo:
    objectinfo:
      gridx: 1
      gridy: 17
      size: 1
    value: 100
    used: false
- iteminfo:
    objectinfo:
      gridx: 22
      gridy: 28
      size: 1
    value: 1000
    used: false
